# The organization for which this configuration applies;
# this must always be set.
organization: myorganization

# The list of org units in this organization. Org units not defined
# here will be deleted during synchronization.
org_units:
  - name: ExampleUnit
    description: test org unit 
    parentOrgUnitPath: / # single slash indicates the parent org
    org_unit_path: /ExampleUnit # single slash followed by the name of the OU

# The list of users in this organization. Users not defined
# here will be deleted during synchronization. 
users:
  - #user 1
    given_name: Horst # first name
    family_name: Example # last name
    # the primary email is a GSuite address
    primary_email: horst@myorganization.com 
    # secondary email is used to send out an invitation
    secondary_email: horst@privateaddress.com
    # org unit path indicates in which OU the user should be created
    org_unit_path: / # single slash indicates parent org

  - given_name: Gregor
    family_name: Samsa
    primary_email: gregor@myorganization.com
    secondary_email: gregor@privatedomain.com
    org_unit_path: /ExampleUnit # create user in beforehand specified OU

# The list of groups and its members in this organization. 
# Groups not defined here will be deleted during synchronization. 
# Members not defined in the group will be removed from it during synchronization.
groups:
  - name: Test Group
    email: testgroup@myorganization.com
    members:
      - email: horst@myorganization.com
        role: MEMBER # role can be MEMBER, OWNER or MANAGER
      - email: gregor@myorganization.com
        role: OWNER
