# The organization for which this configuration applies;
# this must always be set.
organization: myorganization

# The list of users in this organization. Users not defined
# here will be deleted during synchronization. 
users:
  - #user 1
    given_name: Horst # first name
    family_name: Example # last name
    # the primary email is a GSuite address
    primary_email: horst@myorganization.com 
    # secondary email is used to send out an invitation
    secondary_email: horst@privateaddress.com

  - #user N 
    given_name: 
    family_name: 
    primary_email:
    secondary_email:
